
languageCode: en-us
baseURL: "https://ziwei-jiang.github.io/"
title: Ziwei's Site
# paginate: 7
pagination:
  paperSize: 7
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45
googleAnalytics: G-H4P7KF2N8Z
minify:
  disableXML: true
  minifyOutput: true

params:
  social: true
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Ziwei's Blog
  description: "This is the website of Ziwei Jiang, Ph.D. student at Purdue University. "
  keywords: [Causal Inference, Information Theory, Machine Learning, Computer Vision, Natural Language Processing, Robotics]
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  # author: Ziwei Jiang
  disableThemeToggle: false
  ShowWordCount: false
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  
  mainSections:
  - notes
  - projects
  label:
    text: "Ziwei Jiang 姜子维"
    icon: "img/abra_icon.png"
    iconHeight: 35
  assets:
    favicon: "img/abra_icon.png"
    favicon16x16: "img/abra_icon.png"
    favicon32x32: "img/abra_icon.png"
    apple_touch_icon: "img/abra_icon.png"
    safari_pinned_tab: "img/abra_icon.png"
  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: "Welcome! \U0001F44B"
    subtitle: "Hi, my name is Ziwei Jiang. I'm a Ph.D. student at Purdue University working with Professor [Murat Kocaoglu](https://www.muratkocaoglu.com/). My research focuses on **causal inference** and **machine learning** with the **information-theoretic approach**. I'm also interested in computer vision, natural language processing, and robotics."
    imageUrl: "img/profile.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: ""
    buttons:
      - name: Notes
        url: notes
      - name: Projects
        url: projects

  #home-info mode
  homeInfoParams:
    Title: "Welcome! \U0001F44B"
    Content: 
      "Hi, my name is Ziwei Jiang. I'm a Ph.D. student at Purdue University working with Professor [Murat Kocaoglu](https://www.muratkocaoglu.com/). My research focuses on **causal inference** and **machine learning** with the **information-theoretic approach**. I'm also interested in computer vision, natural language processing, and robotics."
  
  

  socialIcons:
    - name: bluesky
      url: "https://ziweijiang.bsky.social"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=FFXwkroAAAAJ&hl=en"
    - name: github
      url: "https://github.com/ziwei-jiang"
    - name: instagram
      url: "https://www.instagram.com/alexjzw/"
    - name: 500px
      url: "https://500px.com/p/ZiweiJiang?view=photos"
    - name: goodreads
      url: "https://www.goodreads.com/user/show/53071850-ziwei-jiang"
    - name: twitter
      url: "https://twitter.com/ziwei_jiang_"
    - name: email
      url: "mailto:alexjiang009@gmail.com"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
#    URL: "https://github.com/chanin-www/content"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 10
    - identifier: notes
      name: Notes
      url: /notes/
      weight: 10

    - identifier: publications
      name: Publications
      url: /publications/
      weight: 10


